import javax.swing.JTable;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
public class BinomialTree_Applet extends javax.swing.JApplet {
    // Private Field Members 
    private double _assetPrice;
    private double _exercisePrice;
    private double _volatility;
    private double _riskFreeRate;
    private double _iteration;
    private double _timeToMaturity;
    private double _p, _u, _d;
    private BinomialTree _btree;
    private JTable jTable1;
    /** Initializes the applet BinomialTree_Applet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
/** This method is called from within the init() method to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {
    jPanel5 = new javax.swing.JPanel();
    jTextField5 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jTextField6 = new javax.swing.JTextField();
    jTextField7 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jTextField9 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jTextField8 = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jComboBox1 = new javax.swing.JComboBox();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jLabel11 = new javax.swing.JLabel();
    jTextField11 = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
                    "OUTPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.
                            border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12),
                    new java.awt.Color(153, 153, 153))); // NOI18N
    jTextField5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField5.setForeground(new java.awt.Color(102, 102, 102));
    jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField5.setToolTipText("[i.e. 100]");
    jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel5.setBackground(new java.awt.Color(153, 153, 153));
    jLabel5.setFont(new java.awt.Font("Arial", 3, 12));
    jLabel5.setForeground(new java.awt.Color(102, 102, 102));
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("_ p _");
    jTextField6.setEditable(false);
    jTextField6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField6.setForeground(new java.awt.Color(102, 102, 102));
    jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jTextField7.setEditable(false);
    jTextField7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField7.setForeground(new java.awt.Color(102, 102, 102));
    jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jLabel7.setBackground(new java.awt.Color(153, 153, 153));
    jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(102, 102, 102));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("_ u _");
    jLabel8.setBackground(new java.awt.Color(153, 153, 153));
    jLabel8.setFont(new java.awt.Font("Arial", 3, 12));
    jLabel8.setForeground(new java.awt.Color(102, 102, 102));
    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("_ d _");
    jTextField9.setEditable(false);
    jTextField9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField9.setForeground(new java.awt.Color(102, 102, 102));
    jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jLabel6.setBackground(new java.awt.Color(153, 153, 153));
    jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
    jLabel6.setForeground(new java.awt.Color(102, 102, 102));
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("ITTERATION");
    jTextField8.setEditable(false);
    jTextField8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField8.setForeground(new java.awt.Color(102, 102, 102));
    jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jLabel9.setBackground(new java.awt.Color(153, 153, 153));
    jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(102, 102, 102));
    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel9.setText("OPTION PRICE");
    jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jButton1.setForeground(new java.awt.Color(102, 102, 102));
    jButton1.setText("CALCULATE");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jButton2.setForeground(new java.awt.Color(102, 102, 102));
    jButton2.setText("DISPLAY BINOMIAL TREE");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel9))))
                            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(17, 17, 17)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                            .addContainerGap())
    );
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
                    "PARAMETERS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial",
                            1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
    jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(102, 102, 102));
    jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField1.setToolTipText("[i.e. 100.14]");
    jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jLabel1.setBackground(new java.awt.Color(153, 153, 153));
    jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
    jLabel1.setForeground(new java.awt.Color(102, 102, 102));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("ASSET PRICE");
    jTextField2.setFont(new java.awt.Font("Arial", 1, 12));
    jTextField2.setForeground(new java.awt.Color(102, 102, 102));
    jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField2.setToolTipText("[i.e. 100.16]");
    jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jLabel2.setBackground(new java.awt.Color(153, 153, 153));
    jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
    jLabel2.setForeground(new java.awt.Color(102, 102, 102));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("EXERCISE PRICE");
    jLabel3.setBackground(new java.awt.Color(153, 153, 153));
    jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
    jLabel3.setForeground(new java.awt.Color(102, 102, 102));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("RISK FREE RATE");
    jTextField3.setFont(new java.awt.Font("Arial", 1, 12));
    jTextField3.setForeground(new java.awt.Color(102, 102, 102));
    jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jLabel4.setBackground(new java.awt.Color(153, 153, 153));
    jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(102, 102, 102));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("VOLATILITY");
    jTextField4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField4.setForeground(new java.awt.Color(102, 102, 102));
    jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                            .addGap(28, 28, 28))
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(22, Short.MAX_VALUE))
    );
    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
                    "OPTION TYPE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1,
                            12), new java.awt.Color(153, 153, 153))); // NOI18N
    jComboBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jComboBox1.setForeground(new java.awt.Color(153, 153, 153));
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "European"}));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });
    jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jRadioButton1.setForeground(new java.awt.Color(102, 102, 102));
    jRadioButton1.setSelected(true);
    jRadioButton1.setText("CALL OPTION");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButton1ActionPerformed(evt);
        }
    });
    jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jRadioButton2.setForeground(new java.awt.Color(102, 102, 102));
    jRadioButton2.setText("PUT OPTION");
    jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButton2ActionPerformed(evt);
        }
    });
    jLabel11.setBackground(new java.awt.Color(153, 153, 153));
    jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(102, 102, 102));
    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel11.setText("TIME TO MATURITY");
    jTextField11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTextField11.setForeground(new java.awt.Color(102, 102, 102));
    jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField11.setToolTipText("[i.e. 0.25 for 3 months]");
    jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                            .addComponent(jRadioButton2))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(20, Short.MAX_VALUE))
    );
    jLabel10.setBackground(new java.awt.Color(153, 153, 153));
    jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
    jLabel10.setForeground(new java.awt.Color(102, 102, 102));
    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel10.setText("Developed by Ioannis Svigkos 2008");
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jLabel10)
                            .addContainerGap(13, Short.MAX_VALUE))
    );
}// </editor-fold>
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            _assetPrice = Double.parseDouble(jTextField1.getText());
            _exercisePrice = Double.parseDouble(jTextField2.getText());
            _riskFreeRate = Double.parseDouble(jTextField3.getText());
            _volatility = Double.parseDouble(jTextField4.getText());
            _iteration = Double.parseDouble(jTextField5.getText());
            _timeToMaturity = Double.parseDouble(jTextField11.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please check values entered!",
                    "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        _btree = new BinomialTree( _assetPrice, _exercisePrice, _riskFreeRate, _volatility, _timeToMaturity, _iteration);
        this._u = roundToEightDecimals(_btree.calculateUpperFactor()); // roundToEightDecimals*/(Math.pow(Math.E, _volatility* Math.sqrt(1/(_iteration-1))));
        this._d = roundToEightDecimals(_btree.calculateLowerFactor()); //*roundToEightDecimals*/(Math.pow(Math.E, -_volatility * Math.sqrt((1/_iteration-1))));
        this._p = roundToEightDecimals(_btree.calculateProbability()); //*roundToEightD ecimals*/((Math.pow(Math.E, _riskFreeRate* ((_iteration-1)))-_d) / (_u - _d));
        jTextField6.setText(String.valueOf(_p));
        jTextField7.setText(String.valueOf(_u));
        jTextField9.setText(String.valueOf(_d));
        if (jComboBox1.getSelectedItem().equals("European")) {
            if (jRadioButton1.isSelected() ) {
                _btree.priceEuropeanCallOption();
                System.out.println(_btree.getEuropeanCallOptionRootPrice());
                jTextField8.setText(String.valueOf(roundToEightDecimals(_btree.getEuropeanCallOptionRootPrice())));
                // _btree.expand();
            } else if (jRadioButton2.isSelected()) {
                _btree.priceEuropeanPutOption();
                jTextField8.setText(String.valueOf(roundToEightDecimals(_btree.getEuropeanPutOptionRootPrice())));
                // _btree.expand();
            }
        }
    }
    public double roundToEightDecimals(double _double) {
        DecimalFormat toEightDecimalForm = new DecimalFormat("#.########");
        return Double.valueOf(toEightDecimalForm.format(_double));
    }
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
            JOptionPane.showMessageDialog(this,
                    "Browser's Security Features Restrict this Action!",
                    "Information Message", JOptionPane.INFORMATION_MESSAGE);
        }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton2.setSelected(false);
        if (!jRadioButton1.isSelected()) {
            jRadioButton1.setSelected(true);
        }
    }
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton1.setSelected(false);
        if (!jRadioButton2.isSelected()) {
            jRadioButton2.setSelected(true);
        }
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration
}